#!/usr/bin/env zsh

DIR=${0:a:h}

DOTFILES=(
  gitconfig
  vimrc
  zshenv
  Xresources
)
for f in $DOTFILES; do
  ln -sf "$DIR/$f" "$HOME/.$f"
done

CONFIG_DIRS=(
  sway
  tmux
)
mkdir -p $HOME/.config
for d in $CONFIG_DIRS; do
  ln -sf "$DIR/$d" "$HOME/.config/"
done

curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
