#! /bin/sh

sxhkd &

# setup dual monitor
xrandr \
    --output DP-1 --primary --mode 2560x1440 --rotate normal \
    --output HDMI-0 --mode 1920x1080 --rotate left --left-of DP-1

xrdb -load $HOME/.Xresources

bspc monitor DP-1 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
